### ISSUE TITLE
License terms are not explicit

### ISSUE THREAD

**Issue by cornwarecjp** [jgarzik/python-bitcoinrpc#42] opened 2015-01-10 18:34 UTC
The docstring in authproxy.py mentions that there is a "Previous copyright, from python-jsonrpc/jsonrpc/proxy.py", which refers to the "GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version."

So, I suppose I can reasonably assume that python-bitcoinrpc is at least *compatible* with LGPL v2.1 or later. However, this still leaves some room for unclarity; I don't think that, the way it is now, I can be 100% certain that all of python-bitcoinrpc is available under LGPL v2.1 or later.

If it is the intention of all contributors to release their contributions under LGPL v2.1 or later (I hope this is the case), then please make it *explicit*.

Also, as a minor note: since the docstring says "You should have received a copy of the GNU Lesser General Public License along with this software", I think you should actually include a copy of the LGPL in the source tree.

**Comment by koobs** [comment] 2015-08-06 15:31
Also, add LICENSE file to repository, and include it in PyPI sdist (using MANIFEST.in)

**Comment by ubldr** [comment] 2015-08-06 16:52
+1

**Comment by MarcoFalke** [comment] 2015-11-23 07:48
Looks like this was fixed by 8fcbaf0ee6ebb0c7930bb35790330f41b879197b

**Comment by koobs** [comment] 2015-11-23 08:27
@MarcoFalke Confirmed, LICENSE is in the latest PyPI 0.3 source distribution (sdist)

**Closed** 2015-11-23 12:59 UTC
